# Khởi chạy server ở cổng 5000
server.port=5000

# Kết nối đến MongoDB cục bộ
spring.data.mongodb.uri=mongodb://localhost:27017/ExpenseManagement

# Cấu hình JWT (dùng cho bước xác thực sau này)
jwt.secret=sichvan_dep_trai_chuoi_nay_can_dai_hon_mot_chut_de_bao_mat
jwt.expiration=2592000000